## https://www.appveyor.com/docs/appveyor-yml/

image: Visual Studio 2022

version: 1.0.{build}

configuration:
  - Debug

platform: Any CPU

environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

init:
  - ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

before_build:
  - appveyor-retry dotnet restore src/AmqpTools.sln -v Minimal
  - set DNX_BUILD_VERSION=%APPVEYOR_BUILD_NUMBER%
  - dotnet --info

build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal

build_script:
  - ps: >-
      ./build.ps1 -runtime win-x64;
      ./build.ps1 -runtime linux-x64;
      ./build.ps1 -runtime linux-musl-x64;

after_build:
  - ps: >-
      $branch = $ENV:APPVEYOR_REPO_BRANCH;
      $fileVersion = $env:APPVEYOR_BUILD_VERSION;
      if($branch -ne 'master') {
          $fileVersion = "${fileVersion}-${branch}"; 
      }

      $fileVersion = $fileVersion.replace("release/", "");
      $fileVersion = $fileVersion.replace("feature/", "");
      $fileVersion = $fileVersion.replace("bugfix/", "");

      gci -include *.csproj -path ((get-location).Path + '/src') -Recurse | %{ 
          if(Test-Path -path $_.Fullname) { 
              dotnet pack $_.Fullname --configuration $env:configuration -o ((get-location).Path + '\artifacts') /property:Version=$fileVersion 
          }
      }

  - cmd: 7z a amqptools.zip -r %APPVEYOR_BUILD_FOLDER%\publish\*
  - cmd: appveyor PushArtifact amqptools.zip

cache:
  - '%USERPROFILE%\.nuget\packages'

nuget:
  disable_publish_on_pr: true

artifacts:
  - path: amqptools.zip
    name: deploy
  - path: artifacts\**\*.*
    name: deploynuget

#deploy:
#  - provider: GitHub
#    description: "$(appveyor_build_version)"
#    auth_token:
#      secure: PfMxiwJ07WiudGV8OdaK1gBnW4kpkcv6mTaCoFj2pdhNPy7QLC5jfSkB4OWwNo35
#    artifact: deploy
#    draft: false
#    prerelease: false
#    on:
#      branch: master # release from master branch only
#  - provider: GitHub
#    description: "$(appveyor_build_version)-develop"
#    auth_token:
#      secure: PfMxiwJ07WiudGV8OdaK1gBnW4kpkcv6mTaCoFj2pdhNPy7QLC5jfSkB4OWwNo35
#    artifact: deploy
#    draft: false
#    prerelease: true
#    on:
#      branch: develop


deploy:
  - provider: NuGet
    artifact: deploynuget
    api_key:
      secure: D7B7/pzGIeteV3H4DrdBtyKCxLrgcBAL6XWtWrm/kJrshDwUZ5acauR9QWll7TWi
